spring.application.name=ai-rag

# DATABASE
spring.datasource.jdbc-url=jdbc:postgresql://192.168.25.79:5432/doc_store
spring.datasource.username=uncledave
spring.datasource.password=Test123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ORACLE
oracle.datasource.jdbc-url=jdbc:oracle:thin:@//ODS-ORADB-03.IIC.IADB.ORG:1521/iicmaed3.subnet1.idbiashburn.oraclevcn.com
oracle.datasource.username=DEV03_IICMAESTRO
oracle.datasource.password=NZ!AQ2pBtdW1jHPAa$
oracle.datasource.driver-class-name=oracle.jdbc.OracleDriver


#spring.ai.model.chat=huggingface

# Hugging Face Chat
spring.ai.huggingface.chat.enabled=true
spring.ai.huggingface.chat.base-url=https://api-inference.huggingface.co/models
spring.ai.huggingface.chat.api-key=
spring.ai.huggingface.chat.options.model=llama2-13b-chat

# Hugging Face Embeddings
spring.ai.huggingface.embedding.enabled=true
spring.ai.huggingface.embedding.base-url=https://api-inference.huggingface.co/pipeline/feature-extraction
spring.ai.huggingface.embedding.api-key=
spring.ai.huggingface.embedding.options.model=sentence-transformers/all-MiniLM-L6-v2

# PGVECTOR
spring.ai.vectorstore.pgvector.jdbc-url=jdbc:postgresql://192.168.25.79:5432/doc_store
spring.ai.vectorstore.pgvector.username=uncledave
spring.ai.vectorstore.pgvector.password=Test123
spring.ai.vectorstore.pgvector.driver-class-name=org.postgresql.Driver
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.dimensions=384

# DOCKER
spring.docker.compose.lifecycle-management=start_only
spring.sql.init.mode=never
spring.docker.compose.enabled=false