spring.application.name=ai-rag

spring.datasource.jdbc-url=jdbc:postgresql://localhost:5432/doc_store
spring.datasource.username=uncledave
spring.datasource.password=Test123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ---------------- Oracle (secundario: solo JdbcTemplate, sin JPA) ----------------
oracle.datasource.jdbc-url=jdbc:oracle:thin:@OTS-ORADB-03.iic.iadb.org:1521/IICBPMP.subnet1.idbiashburn.oraclevcn.com
oracle.datasource.username=IICBPMPRD
oracle.datasource.password=y%q2LRWQhx#Sl@j853IQ
oracle.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ---------------- pgvector (Spring AI: separado de JPA) ----------------
spring.ai.vectorstore.pgvector.jdbc-url=jdbc:postgresql://localhost:5432/doc_store
spring.ai.vectorstore.pgvector.username=uncledave
spring.ai.vectorstore.pgvector.password=Test123
spring.ai.vectorstore.pgvector.driver-class-name=org.postgresql.Driver
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.dimensions=1536

# ---------------- Config OpenAI ----------------
spring.ai.openai.api-key=${OAI-API-KEY}
spring.ai.openai.chat.options.model=gpt-4o

# ---------------- Otros ----------------
spring.docker.compose.lifecycle-management=start_only
spring.sql.init.mode=never
