spring.application.name=ai-rag

# Configuración de la base de datos Oracle
spring.datasource.url=jdbc:oracle:thin:@OTS-ORADB-03.iic.iadb.org:1521/IICBPMP.subnet1.idbiashburn.oraclevcn.com
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=IICBPMPRD
spring.datasource.password=y%q2LRWQhx#Sl@j853IQ

# Configuración JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Configuración de OpenAI
spring.ai.openai.api-key=${OAI-API-KEY}
spring.ai.openai.chat.options.model=gpt-4o

# Configuración de pgvector
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.dimensions=1536

spring.docker.compose.lifecycle-management=start_only
spring.sql.init.mode=never
